<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="MainPackage"
    nsURI="http://gts.inf.um.es/rubytl/test/packages" nsPrefix="packages">
  <eClassifiers xsi:type="ecore:EClass" name="ClassInMainPackage">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Model">
    <eStructuralFeatures xsi:type="ecore:EReference" name="objects" upperBound="-1"
        eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject" containment="true"/>
  </eClassifiers>
  <eSubpackages name="Subpackage" nsURI="http://gts.inf.um.es/rubytl/test/packages/subpackages"
      nsPrefix="subpackage">
    <eClassifiers xsi:type="ecore:EClass" name="ClassInSubpackage"/>
    <eClassifiers xsi:type="ecore:EClass" name="InheritingClass" eSuperTypes="#//ClassInMainPackage"/>
  </eSubpackages>
</ecore:EPackage>
